# Configuring the CRDs for cert-manager
# Require cert-manager to be installed first
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: local-selfsigned-ca
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca-issuer
spec:
  ca:
    secretName: root-ca-secret
---
#### Components certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-main-crt
  namespace: cdk-deps
spec:
  isCA: false
  secretName: pg-main-crt-secret
  subject:
    organizations:
      - main-postgresql
  commonName: main-postgresql.cdk-deps.svc.cluster.local
  dnsNames:
    - "main-postgresql.cdk-deps.svc.cluster.local"
    - "*.main-postgresql-hl.cdk-deps.svc.cluster.local"
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-sql-crt
  namespace: cdk-deps
spec:
  isCA: false
  secretName: pg-sql-crt-secret
  subject:
    organizations:
      - sql-postgresql
  commonName: sql-postgresql.cdk-deps.svc.cluster.local
  dnsNames:
    - "sql-postgresql.cdk-deps.svc.cluster.local"
    - "*.sql-postgresql-hl.cdk-deps.svc.cluster.local"
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: s3-crt
  namespace: cdk-deps
spec:
  isCA: false
  secretName: s3-crt-secret
  subject:
    organizations:
      - s3-minio
  commonName: s3-minio.cdk-deps.svc.cluster.local
  dnsNames:
    - s3-minio.cdk-deps.svc.cluster.local
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-jks-password-secret
  namespace: cdk-deps
type: Opaque
stringData:
  password: "conduktor"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-crt
  namespace: cdk-deps
spec:
  isCA: false
  secretName: keycloak-crt-secret
  subject:
    organizations:
      - keycloak
  commonName: oidc.localhost
  dnsNames:
    - oidc.localhost
    - keycloak.cdk-deps.svc.cluster.local
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: keycloak-jks-password-secret
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: conduktor-console-jks-password-secret
  namespace: conduktor
type: Opaque
stringData:
  password: "conduktor"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-console-crt
  namespace: conduktor
spec:
  isCA: false
  secretName: custom-console-crt-secret
  subject:
    organizations:
      - conduktor
  commonName: console.conduktor.localhost
  dnsNames:
    - console.conduktor.localhost
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: conduktor-console-jks-password-secret
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: conduktor-gateway-jks-password-secret
  namespace: conduktor
type: Opaque
stringData:
  password: "conduktor"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: conduktor
spec:
  isCA: false
  secretName: gateway-tls-secret
  subject:
    organizations:
      - conduktor
  commonName: gateway.conduktor.localhost
  dnsNames:
    - gateway.conduktor.localhost
    - "*.gateway.conduktor.localhost"
    - conduktor-gateway-internal.conduktor.svc.cluster.local
    - "*.conduktor-gateway-internal.conduktor.svc.cluster.local"
    - conduktor-gateway-external.conduktor.svc.cluster.local
    - "*.conduktor-gateway-external.conduktor.svc.cluster.local"
  issuerRef:
    name: local-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: conduktor-gateway-jks-password-secret
        key: password
---