bootstrap.servers=gateway.conduktor.test:9092

# Security protocol
security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER

# SASL OAUTH configuration
sasl.oauthbearer.method=oidc
sasl.oauthbearer.client.id=app-1
sasl.oauthbearer.client.secret=app-1-secret
sasl.oauthbearer.scope=email
sasl.oauthbearer.token.endpoint.url=https://oidc.conduktor.test/realms/conduktor-realm/protocol/openid-connect/token
# Your IdP may require configuring sub claim name. If so, make sure it matches the value of GATEWAY_OAUTH_SUB_CLAIM_NAME in gateway-values.yaml.
sasl.oauthbearer.assertion.claim.sub=azp

# SSL settings
ssl.ca.location=./ca.crt
https.ca.location=./ca.crt