#####
# Secrets for Conduktor Console + Cortex
# In real customer environment, secrets should be managed by a secret manager and not sit unencrypted in a git repository !
#####
apiVersion: v1
kind: Secret
metadata:
  name: console-secrets
  namespace: conduktor
type: Opaque
stringData: # use stringData to avoid base64 encoding for demo. Don't do this in production and rely on secret manager to provide secrets

  CDK_LICENSE: "<conduktor license>"  # Replaced with content of LICENSE environment variable

  # Root admin local user
  CDK_ADMIN_EMAIL: "admin@company.io"
  CDK_ADMIN_PASSWORD: "adminP4ss!"

  # Main database
  CDK_DATABASE_USERNAME: "postgres"
  CDK_DATABASE_PASSWORD: "conduktor"
  # SQL database
  CDK_KAFKASQL_DATABASE_USERNAME: "postgres"
  CDK_KAFKASQL_DATABASE_PASSWORD: "conduktor"

  # Custom Environment Variables expended in .Values.config
  SSO_CLIENT_ID: "conduktor-oidc"
  SSO_CLIENT_SECRET: "8d0Y8oHCHhRIdJ2fouU56mwv64YAxbyO" # secret set on Keycloak realm import (./local-stack/03-components/keycloak.yaml)

  CDK_SSL_TRUSTSTORE_PASSWORD: "conduktor"
---
apiVersion: v1
kind: Secret
metadata:
  name: console-cortex-secrets
  namespace: conduktor
type: Opaque
stringData:
  CDK_MONITORING_STORAGE_S3_ACCESSKEYID: "admin"
  CDK_MONITORING_STORAGE_S3_SECRETACCESSKEY: "conduktor"